import sys
from core.agents.coordinator import CoordinatorAgent

def main():
    print("Initializing IMPACT Multi-Agent Evolution Tracker...")
    coordinator = CoordinatorAgent()
    
    import os
    package_dir = os.path.dirname(os.path.abspath(__file__))
    file_v1 = os.path.join(package_dir, "schema", "v1_graph.json")
    file_v2 = os.path.join(package_dir, "schema", "v2_graph.json")
    
    intents = [
        "avoid cyclic dependencies",
        "minimize changes and complexity increase"
    ]
    
    print("\n--- Running Evolution Analysis ---")
    report = coordinator.run_analysis(file_v1, file_v2, intents)
    
    print("\n--- Analysis Report Generated by Swarm ---")
    print(report)

if __name__ == "__main__":
    main()
